# Generated by Django 3.2.4 on 2021-06-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameManagement',
            fields=[
                ('student_number', models.PositiveIntegerField(help_text='出席番号．ユニークな値であること．', primary_key=True, serialize=False, unique=True, verbose_name='出席番号')),
                ('last_name', models.CharField(max_length=30, verbose_name='苗字')),
                ('first_name', models.CharField(max_length=30, verbose_name='名前')),
                ('rubi', models.CharField(default='None', max_length=60, verbose_name='ふりがな')),
                ('active', models.BooleanField(default=1, help_text='席替えの有効化の設定．チェックをオフにすると席替えで配置されないので注意．', verbose_name='有効化')),
            ],
        ),
        migrations.CreateModel(
            name='SeatManagement',
            fields=[
                ('seat_number', models.PositiveIntegerField(help_text='席番号の入力．ユニークな値であること．', primary_key=True, serialize=False, unique=True, verbose_name='席番号')),
                ('lk', models.BooleanField(default=0, help_text='初期化されない為に固定する人はチェックを入れること．', verbose_name='席のロック')),
                ('weight', models.PositiveIntegerField(help_text='シャッフルの際の席の重みをつけることにより，サーバー処理による乱数発生の偏りを解決する．', verbose_name='席の重み')),
                ('name', models.ForeignKey(blank=True, help_text='座席の指定．シャッフルを行う前に必ず指定しておくこと．', null=True, on_delete=django.db.models.deletion.CASCADE, to='four_information.namemanagement', verbose_name='名前')),
            ],
        ),
        migrations.CreateModel(
            name='SeatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateTimeField(null=True, verbose_name='実行日時')),
                ('h_name', models.ForeignKey(help_text='座席履歴．過去の座席履歴の保存．編集禁止！！！！', null=True, on_delete=django.db.models.deletion.CASCADE, to='four_information.namemanagement', verbose_name='名前')),
                ('seat_number', models.ForeignKey(help_text='座席番号．ユニークな値であること．', on_delete=django.db.models.deletion.CASCADE, to='four_information.seatmanagement', verbose_name='座席番号')),
            ],
        ),
    ]
