# Generated by Django 3.2.4 on 2021-06-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namemanagement',
            name='rubi',
            field=models.CharField(max_length=60, verbose_name='ふりがな'),
        ),
    ]
