# Generated by Django 3.2.4 on 2021-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_information', '0002_alter_namemanagement_rubi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seathistory',
            name='save_date',
            field=models.DateTimeField(default='2021-04-01 00:00:00', verbose_name='実行日時'),
        ),
    ]
