# Generated by Django 3.2.4 on 2021-06-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_information', '0003_alter_seathistory_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seathistory',
            name='save_date',
            field=models.DateTimeField(default='2021-03-31 21:00:00', verbose_name='実行日時'),
        ),
    ]
