# Generated by Django 3.2.4 on 2021-06-10 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('four_information', '0004_alter_seathistory_save_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seathistory',
            name='save_date',
            field=models.DateTimeField(verbose_name='実行日時'),
        ),
        migrations.AlterField(
            model_name='seathistory',
            name='seat_number',
            field=models.ForeignKey(help_text='座席番号．', on_delete=django.db.models.deletion.CASCADE, to='four_information.seatmanagement', verbose_name='座席番号'),
        ),
    ]
