# Generated by Django 3.2.4 on 2021-06-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_information', '0005_auto_20210610_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.PositiveIntegerField(verbose_name='ゾーンの番号．')),
                ('seat', models.ManyToManyField(to='four_information.SeatManagement')),
            ],
        ),
    ]
