# Generated by Django 3.2.4 on 2021-06-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_information', '0006_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatmanagement',
            name='lk',
            field=models.BooleanField(default=0, help_text='固定する人はチェックを入れること．', verbose_name='席のロック'),
        ),
    ]
